#version: "3.9"
services:
  app:
    build:
      context: . # Dockerfile in same dir.
      args:
        - DEV=true
    ports:
      - "8000:8000"
    volumes:
      - ./app:/app # Syncs the app directory in local
    command: >
      sh -c "python manage.py wait_for_db &&
             python manage.py migrate &&
             python manage.py runserver 0.0.0.0:8000"
    environment:
      - DB_HOST=db
      - DB_NAME=devdb
      - DB_USER=devuser
      - DB_PASS=changeme
      - GEMINI_API_KEY=$GEMINI_API_KEY
    depends_on:
      - db

  db:
    image: postgres:13-alpine
    volumes:
      - dev-db-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=devdb
      - POSTGRES_USER=devuser
      - POSTGRES_PASSWORD=changeme

  pgadmin:
    image: dpage/pgadmin4:latest
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@example.com # Default pgAdmin login email
      - PGADMIN_DEFAULT_PASSWORD=admin         # Default pgAdmin login password
    ports:
      - "5050:80" # Expose pgAdmin on port 5050
    depends_on:
      - db # Ensure the PostgreSQL service is started before pgAdmin

volumes:
  dev-db-data:
